export const text = [
	"Starting new game...",
	"Fetching a random Wikipedia article...",
	"Almost there!",
	"Preparing your game...",
	"Loading fun...",
	"Getting things ready...",
	"Hang tight, loading...",
	"Just a moment more...",
	"Setting up your adventure...",
	"Loading excitement...",
	"Getting your game ready...",
	"Preparing a challenge for you...",
	"Loading knowledge...",
	"Fetching trivia...",
	"Almost ready to play...",
	"Loading the fun...",
	"Getting everything set...",
	"Preparing your challenge...",
	"Loading up the game...",
	"Just a sec, loading...",
];
